openapi: 3.0.0
info:
  title: Indico Fastlane Integration
  description: "This is a draft for a REST API to be provided by an [Indico](https://indico.cern.ch/)\
    \ plugin. The API will be consumed by a [fastlane](https://docs.fastlane.tools/)\
    \ environment to provide continuous delivery of [Flutter](https://flutter.dev/)\
    \ applications. It provides metadata for distribution in the Apple App Store via\
    \ [App Store Connect](https://flutter.dev/) and [Google Play Store](https://play.google.com/console)\
    \ as well as basic data for instantiating a new application. \n"
  contact:
    email: arnold.arz@uni-muenster.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Arceoavs/indico-fastlane/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: iOS
  description: Basic information used by the fastlane tools for delivery to App Store
    Connect
- name: Android
  description: Basic information used by the fastlane tools for delivery to the Google
    Play Console
- name: Flutter
  description: Basic information used for instanciating a new Flutter application
paths:
  /appfile/{appId}:
    get:
      tags:
      - iOS
      summary: Get Appfile data by ID
      description: Basic information in the [Appfile](https://docs.fastlane.tools/advanced/Appfile/)
        that is used accross all fastlane tools
      operationId: getAppfileDataById
      parameters:
      - name: appId
        in: path
        description: ID of application to return appfile data for
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Application not found
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appfile'
  /deliverfile/{appId}:
    get:
      tags:
      - iOS
      summary: Get Deliverfile data by ID
      description: Various App Store Connect metadata in the [Deliverfile](https://docs.fastlane.tools/actions/deliver/)
        accross all fastlane tools
      operationId: getDeliverfileDataById
      parameters:
      - name: appId
        in: path
        description: ID of application to return appfile data for
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Application not found
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deliverfile'
  /matchfile/{appId}:
    get:
      tags:
      - iOS
      summary: Get Matchfile data by ID
      description: Code signing information in the [Matchfile](https://docs.fastlane.tools/actions/match/)
        accross all fastlane tools
      operationId: getMatchfileDataById
      parameters:
      - name: appId
        in: path
        description: ID of application to return appfile data for
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Application not found
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Matchfile'
  /snapfile/{appId}:
    get:
      tags:
      - iOS
      summary: Get Snapfile data by ID
      description: Device information in the [Snapfile](https://github.com/mmcc007/screenshots)
        to create automated Screenshots in UI test
      operationId: getSnapfileDataById
      parameters:
      - name: appId
        in: path
        description: ID of application to return appfile data for
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Application not found
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Snapfile'
  /metadata/{appId}:
    get:
      tags:
      - iOS
      summary: Get metadata for app
      description: Metadata to be displayed in the App Store using fastlane [deliver](https://docs.fastlane.tools/actions/deliver/)
      operationId: getMetadataById
      parameters:
      - name: appId
        in: path
        description: ID of application to return appfile data for
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Application not found
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metadata'
components:
  schemas:
    Appfile:
      type: object
      properties:
        app_name:
          type: string
          description: The name of the Flutter application
          example: Flutter Hello World App
        app_identifier:
          type: array
          description: The application bundle IDs in reverse domain format
          example:
          - berlin.arz.flutter.helloworld
          items:
            type: string
        username:
          type: string
          description: App store connect user e-mail address
          example: user@example.com
        path_on_ci:
          type: string
          description: Build context path on the CI system
          example: /Users/builder/hello_world
    Deliverfile:
      type: object
      properties:
        languages:
          type: array
          description: List of languages that are supported
          example:
          - en-US
          - de-DE
          items:
            type: string
        username:
          type: string
          description: App store connect user e-mail address
          example: user@example.com
        price_tier:
          type: integer
          description: The [price tier](https://help.apple.com/app-store-connect/#/dev9fc06e23d)
            in App Store connect
          example: 0
    Matchfile:
      type: object
      properties:
        app_identifier:
          type: array
          description: The application bundle IDs in reverse domain format
          example:
          - berlin.arz.flutter.helloworld
          items:
            type: string
        storage_mode:
          type: string
          description: Storage mode of code signing credentials
          example: git
        git_url:
          type: string
          description: URL to (private) git repository to retrieve appstore profile
            information
          example: https://github.com/User/repository
        type:
          type: string
          description: The default type, can be adhoc, enterprise or development
          example: appstore
        username:
          type: string
          description: App store connect user e-mail address
          example: user@example.com
    Snapfile:
      type: object
      properties:
        devices:
          type: array
          description: List of devices that the UI test should run on
          example:
          - iPhone 8
          - iPhone 8 Plus
          - iPhone SE
          - iPhone X
          - iPad Pro (12.9-inch)
          - iPad Pro (9.7-inch)
          - Apple TV 1080p
          items:
            type: string
        languages:
          type: array
          description: List of languages that are supported
          example:
          - en-US
          - de-DE
          items:
            type: string
    Metadata:
      type: object
      properties:
        copyright:
          type: string
          description: Copyright information
          example: Copyright 2020-2021 Max Mustermann
        primary_category:
          type: string
          description: Primary [App Store Category](https://developer.apple.com/app-store/categories/)
          example: Productivity
        primary_first_sub_category:
          type: string
          description: Primary first [App Store Sub-Category](https://developer.apple.com/app-store/categories/).
            Probably empty if not a game
          example: ""
        primary_second_sub_category:
          type: string
          description: Primary second [App Store Sub-Category](https://developer.apple.com/app-store/categories/).
            Probably empty if not a game
          example: ""
        secondary_category:
          type: string
          description: Secondary [App Store Category](https://developer.apple.com/app-store/categories/)
          example: Education
        secondary_first_sub_category:
          type: string
          description: Secondary first [App Store Sub-Category](https://developer.apple.com/app-store/categories/).
            Probably empty if not a game
          example: ""
        secondary_second_sub_category:
          type: string
          description: Secondary second [App Store Sub-Category](https://developer.apple.com/app-store/categories/).
            Probably empty if not a game
          example: ""
        review_information:
          $ref: '#/components/schemas/Metadata_review_information'
        languages:
          type: array
          items:
            $ref: '#/components/schemas/Metadata_languages'
    Metadata_review_information:
      type: object
      properties:
        demo_password:
          type: string
          description: Password for the demo user for code review
          example: "123456"
        demo_user:
          type: string
          description: Username for the demo user for code review
          example: User123
        email_address:
          type: string
          description: E-Mail address for contact in code review
          example: user@example.com
        first_name:
          type: string
          description: First name for code review
          example: Max
        last_name:
          type: string
          description: Last name for code review
          example: Mustermann
        notes:
          type: string
          description: Notes for code review
          example: Use the big blue button to do big blue things
        phone_number:
          type: string
          description: Phone number for code review
          example: +49 12345678
    Metadata_languages:
      type: object
      properties:
        id:
          type: string
          description: language identifier
          example: en-US
        apple_tv_privacy_policy:
          type: string
          description: Privacy policy for apple TV apps
          example: ""
        description:
          type: string
          description: App Store description
          example: This app does things. Sometimes even well.
        keywords:
          type: string
          description: Comma-separated keywords list
          example: hello, world, fluter, indico
        marketing_url:
          type: string
          description: URL to the marketing website
          example: www.example.com/marketing
        name:
          type: string
          description: Application name in the App Store
          example: Hello World App
        privacy_url:
          type: string
          description: URL to the privacy policy of the developer
          example: www.example.com/privacy
        promotional_text:
          type: string
          description: Promotional text for App Store promotions
          example: This app is really good. Trust me
        release_notes:
          type: string
          description: Release notes for the application
          example: Bug fixes
        subtitle:
          type: string
          description: Subtitle for the application in the App Store
          example: Virtual events
        support_url:
          type: string
          description: URL for support from the developer
          example: www.example.com/support
