openapi: 3.0.0
info:
  title: Swagger Petstore
  description: "This is a draft for a REST API to be provided by an [Indico](https://indico.cern.ch/)\
    \ plugin. The API will be consumed by a [fastlane](https://docs.fastlane.tools/)\
    \ environment to provide continuous delivery of [Flutter](https://flutter.dev/)\
    \ applications. It provides metadata for distribution in the Apple App Store via\
    \ [App Store Connect](https://flutter.dev/) and [Google Play Store](https://play.google.com/console)\
    \ as well as basic data for instantiating a new application. \n"
  contact:
    email: arnold.arz@uni-muenster.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Arceoavs/indico-fastlane/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: iOS
  description: Basic information used by the fastlane tools for delivery to App Store
    Connect
- name: Android
  description: Basic information used by the fastlane tools for delivery to the Google
    Play Console
- name: Flutter
  description: Basic information used for instanciating a new Flutter application
paths:
  /appfile/{appId}:
    get:
      tags:
      - iOS
      summary: Get Appfile data by ID
      description: Blabla
      operationId: getAppfileDataById
      parameters:
      - name: appId
        in: path
        description: ID of application to return appfile data for
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Application not found
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appfile'
components:
  schemas:
    Appfile:
      type: object
      properties:
        app_name:
          type: string
          description: The name of the Flutter application
          example: Flutter Hello World App
        app_identifier:
          type: array
          description: The application bundle IDs in reverse domain format
          example:
          - berlin.arz.flutter.helloworld
          items:
            type: string
        username:
          type: string
          description: App store connect user e-mail address
          example: user@example.com
        path_on_ci:
          type: string
          description: Build context path on the CI system
          example: /Users/builder/hello_world
