openapi: 3.0.0
info:
  title: Indico Fastlane Integration
  description: "This is a draft for a REST API to be provided by an [Indico](https://indico.cern.ch/)\
    \ plugin. The API will be consumed by a [fastlane](https://docs.fastlane.tools/)\
    \ environment to provide continuous delivery of [Flutter](https://flutter.dev/)\
    \ applications. It provides metadata for distribution in the Apple App Store via\
    \ [App Store Connect](https://flutter.dev/) and [Google Play Store](https://play.google.com/console)\
    \ as well as basic data for instantiating a new application. \n"
  contact:
    email: arnold.arz@uni-muenster.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Arceoavs/indico-fastlane/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: iOS
  description: Basic information used by the fastlane tools for delivery to App Store
    Connect
- name: Android
  description: Basic information used by the fastlane tools for delivery to the Google
    Play Console
- name: Flutter
  description: Basic information used for instanciating a new Flutter application
paths:
  /appfile/{appId}:
    get:
      tags:
      - iOS
      summary: Get Appfile data by ID
      description: Basic information in the [Appfile](https://docs.fastlane.tools/advanced/Appfile/)
        that is used accross all fastlane tools
      operationId: getAppfileDataById
      parameters:
      - name: appId
        in: path
        description: ID of application to return appfile data for
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Application not found
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appfile'
  /deliverfile/{appId}:
    get:
      tags:
      - iOS
      summary: Get Deliverfile data by ID
      description: Various App Store Connect metadata in the [Deliverfile](https://docs.fastlane.tools/actions/deliver/)
        accross all fastlane tools
      operationId: getDeliverfileDataById
      parameters:
      - name: appId
        in: path
        description: ID of application to return appfile data for
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Application not found
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deliverfile'
  /matchfile/{appId}:
    get:
      tags:
      - iOS
      summary: Get Matchfile data by ID
      description: Code signing information in the [Matchfile](https://docs.fastlane.tools/actions/match/)
        accross all fastlane tools
      operationId: getMatchfileDataById
      parameters:
      - name: appId
        in: path
        description: ID of application to return appfile data for
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Application not found
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Matchfile'
components:
  schemas:
    Appfile:
      type: object
      properties:
        app_name:
          type: string
          description: The name of the Flutter application
          example: Flutter Hello World App
        app_identifier:
          type: array
          description: The application bundle IDs in reverse domain format
          example:
          - berlin.arz.flutter.helloworld
          items:
            type: string
        username:
          type: string
          description: App store connect user e-mail address
          example: user@example.com
        path_on_ci:
          type: string
          description: Build context path on the CI system
          example: /Users/builder/hello_world
    Deliverfile:
      type: object
      properties:
        languages:
          type: array
          description: List of languages that are supported
          example:
          - en-US
          - de-DE
          items:
            type: string
        username:
          type: string
          description: App store connect user e-mail address
          example: user@example.com
        price_tier:
          type: integer
          description: The [price tier](https://help.apple.com/app-store-connect/#/dev9fc06e23d)
            in App Store connect
          example: 0
    Matchfile:
      type: object
      properties:
        app_identifier:
          type: array
          description: The application bundle IDs in reverse domain format
          example:
          - berlin.arz.flutter.helloworld
          items:
            type: string
        storage_mode:
          type: string
          description: Storage mode of code signing credentials
          example: git
        git_url:
          type: string
          description: URL to (private) git repository to retrieve appstore profile
            information
          example: https://github.com/User/repository
        type:
          type: string
          description: The default type, can be adhoc, enterprise or development
          example: appstore
        username:
          type: string
          description: App store connect user e-mail address
          example: user@example.com
